//! GEMM tile + rocBLAS solution-index tuning tables.
//!
//! Two shape-indexed lookup helpers used by the matmul path:
//! - [`lookup_gemm_config`] — per-(m, n, k, wave) tile selection to keep
//!   small decode `m` shapes from being starved by big prefill tiles.
//! - [`lookup_solution_index`] — offline-benchmarked rocBLAS
//!   `gemm_ex` solution indices for shapes seen at inference time
//!   (Llama/Gemma decode + prefill). Falls back to `0` (standard)
//!   for untuned shapes. Generated by `examples/tune_gemm.rs` on
//!   gfx1036.
//!
//! Skill attribution:
//! - `rocm-profiling-perf` — autotune loop methodology and the runtime
//!   `rocblas_gemm_ex_get_solutions` enumeration the lookup eventually
//!   replaces.
//! - `rust-gpu-discipline` §4 — fall back to the safe default (index 0)
//!   for unknown shapes; never panic on a miss.

use grim_tensor::ArithType;

use crate::WavefrontSize;

/// Tile selector for the rocBLAS GEMM path. Each field is a power-of-two
/// multiple of the wavefront size (32 or 64, depending on arch).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GemmTileConfig {
    pub block_m: u32,
    pub block_n: u32,
    pub block_k: u32,
}

/// Shape-indexed GEMM tile selection for prefill vs. decode shapes.
///
/// Prefill: large `m`, `n`, `k` → use large tiles for max throughput.
/// Decode:  `m` is very small (1–8) → use small `block_m` to avoid
/// thread-wasting + latency.
pub fn lookup_gemm_config(m: usize, n: usize, k: usize, wave: WavefrontSize) -> GemmTileConfig {
    match wave {
        WavefrontSize::W64 => {
            if m <= 8 {
                // Decode / small-batch path
                GemmTileConfig {
                    block_m: 8,
                    block_n: if n % 64 == 0 { 64 } else { 32 },
                    block_k: if k % 64 == 0 { 64 } else { 32 },
                }
            } else {
                // Prefill / large-batch path
                GemmTileConfig {
                    block_m: if m % 128 == 0 { 128 } else { 64 },
                    block_n: if n % 128 == 0 { 128 } else { 64 },
                    block_k: 32,
                }
            }
        }
        WavefrontSize::W32 => {
            if m <= 8 {
                GemmTileConfig {
                    block_m: 4,
                    block_n: if n % 32 == 0 { 32 } else { 16 },
                    block_k: if k % 32 == 0 { 32 } else { 16 },
                }
            } else {
                GemmTileConfig {
                    block_m: if m % 64 == 0 { 64 } else { 32 },
                    block_n: if n % 64 == 0 { 64 } else { 32 },
                    block_k: 16,
                }
            }
        }
    }
}

/// Offline-tuned rocBLAS solution index lookup table (Item 7).
///
/// Keys are `(m, n, k, arith)` tuples representing shapes seen in real
/// inference (Llama/Gemma prefill + decode). Values are the fastest
/// `solution_index` from `rocblas_gemm_ex_get_solutions` benchmarks. Falls
/// back to `0` (standard) for untuned shapes.
///
/// Generated by running `examples/tune_gemm.rs` on gfx1036
/// (AMD Radeon 610M). Other dtypes/shapes will be added as they are tuned.
pub fn lookup_solution_index(m: usize, n: usize, k: usize, arith: ArithType) -> i32 {
    // Only tuned for FP32 on gfx1036 so far; other dtypes fall back to 0.
    if arith != ArithType::F32 {
        return 0;
    }
    match (m, n, k) {
        // Decode shapes (m=1,8)
        (1, 4096, 4096) => 4,
        (8, 4096, 4096) => 11,
        (1, 11008, 4096) => 65,
        (8, 11008, 4096) => 1,
        // Prefill shapes can be added here as they are tuned.
        _ => 0,
    }
}

#[cfg(any(test, feature = "loom-test"))]
mod loom_tests {
    use super::*;

    /// The lookup must be deterministic across calls so the autotune
    /// cache (Phase-3 §3.6) gets stable keys.
    #[test]
    fn lookup_solution_index_deterministic_within_shape() {
        assert_eq!(lookup_solution_index(1, 4096, 4096, ArithType::F32), 4);
        assert_eq!(lookup_solution_index(8, 4096, 4096, ArithType::F32), 11);
        // Off-table shapes must take the F32-off path even when the inputs
        // would otherwise match (here, a non-4096 k-dim).
        assert_eq!(lookup_solution_index(1, 4096, 1024, ArithType::F32), 0);
        // Non-F32 arith types must always fall back to 0 even for
        // on-table shapes — those entries were tuned for FP32 only.
        assert_eq!(
            lookup_solution_index(1, 4096, 4096, ArithType::F16),
            0
        );
    }

    #[test]
    fn lookup_gemm_config_w64_decode_uses_small_m() {
        let cfg = lookup_gemm_config(1, 4096, 4096, WavefrontSize::W64);
        assert_eq!(cfg.block_m, 8);
    }

    #[test]
    fn lookup_gemm_config_w64_prefill_uses_large_tiles() {
        let cfg = lookup_gemm_config(64, 4096, 4096, WavefrontSize::W64);
        assert!(cfg.block_m >= 64);
    }
}
