#!/usr/bin/env python3
"""Assemble the IQ2_S oracle C programs from llama.cpp's actual sources.

Everything the oracle needs — the functions, the tables, the fp16 conversion —
is extracted VERBATIM from `old/repo/llama.cpp-master/ggml/src/` by this script
and written as standalone C, compiled with cc. Nothing is retyped by hand; a
previous generator emitted the table COUNTS as initializers
(`iq2s_grid[1024] = {1024}`), producing an oracle with an all-zero grid that
"validated" nothing.

Usage:
    python3 tools/gen_iq2s_oracle.py           # builds /tmp/iq2s_oracle/{oracle,quant_oracle}

Outputs:
    /tmp/iq2s_oracle/oracle        stdin: packed IQ2_S bytes -> stdout: dequantized f32
    /tmp/iq2s_oracle/quant_oracle  stdin: f32 row(s), each a multiple of 256
                                           -> stdout: quantize_row_iq2_s_ref bytes
"""

import os
import re
import subprocess
import sys

REPO = os.environ.get(
    "LLAMA_CPP_REF", os.path.join(os.path.dirname(__file__), "..", "..", "..", "old", "repo", "llama.cpp-master")
)
GGML_SRC = os.path.join(REPO, "ggml", "src")
OUT_DIR = "/tmp/iq2s_oracle"


def read(path: str) -> str:
    with open(os.path.join(GGML_SRC, path)) as f:
        return f.read()


def extract_function(src: str, signature: str) -> str:
    """Cut `signature ... { ... }` (brace-matched) out of `src`, verbatim."""
    i = src.find(signature)
    if i < 0:
        raise SystemExit(f"signature not found: {signature!r}")
    start = src.index("{", i)
    depth = 0
    for j in range(start, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return src[i : j + 1]
    raise SystemExit(f"unbalanced braces for: {signature!r}")


def extract_table(src: str, name: str) -> str:
    """Extract a GGML_TABLE_BEGIN/END block or a `static const T name[n] = {...};`."""
    m = re.search(rf"GGML_TABLE_BEGIN\((\w+), {name}, (\d+)\)", src)
    if m:
        start = src.index("\n", m.start()) + 1
        end = src.index("GGML_TABLE_END()", start)
        return f"static const {m.group(1)} {name}[{m.group(2)}] = {{{src[start:end]}}};"
    m = re.search(rf"static const (\w+) {name}\[\d+\] = \{{(.*?)\}};", src, re.S)
    if m:
        return f"static const {m.group(1)} {name}[] = {{{m.group(2)}}};"
    raise SystemExit(f"table not found: {name}")


# ---------------------------------------------------------------- shared part
quants_c = read("ggml-quants.c")
impl_h = read("ggml-impl.h")
common_h = read("ggml-common.h")

fp16_bits = "".join(
    extract_function(impl_h, sig)
    for sig in (
        "static inline float fp32_from_bits(",
        "static inline uint32_t fp32_to_bits(",
        "static inline float ggml_compute_fp16_to_fp32(",
        "static inline ggml_fp16_t ggml_compute_fp32_to_fp16(",
    )
)

header = f"""// GENERATED by crates/grim-quant/tools/gen_iq2s_oracle.py from
// old/repo/llama.cpp-master/ggml/src/ -- do not edit by hand.
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <math.h>
#include <float.h>
#define GGML_FP16_TO_FP32(x) ggml_compute_fp16_to_fp32((ggml_fp16_t)(x))
#define GGML_FP32_TO_FP16(x) ggml_compute_fp32_to_fp16((float)(x))
#define QK_K 256
#define GGML_RESTRICT __restrict__
typedef uint16_t ggml_fp16_t;
typedef uint16_t ggml_half_t;
typedef struct {{ ggml_half_t d; uint8_t qs[QK_K/4]; uint8_t qh[QK_K/32]; uint8_t scales[QK_K/32]; }} block_iq2_s;
{fp16_bits}
{extract_table(common_h, 'iq2s_grid')}
{extract_table(common_h, 'kmask_iq2xs')}
"""

# ------------------------------------------------------------------ dequant
dequant_oracle = (
    header
    + "\n"
    + extract_function(quants_c, "void dequantize_row_iq2_s(")
    + """

int main(void) {
    unsigned char * in = malloc(1 << 24);
    float * y = malloc(1 << 24);
    size_t len = fread(in, 1, 1 << 24, stdin);
    size_t nblocks = len / 82;
    if (nblocks == 0 || len % 82 != 0) { fprintf(stderr, "bad input len %zu\\n", len); return 1; }
    for (size_t i = 0; i < nblocks; ++i)
        dequantize_row_iq2_s((const block_iq2_s *)(in + i*82), y + i*256, 256);
    fwrite(y, 4, nblocks*256, stdout);
    return 0;
}
"""
)

# ------------------------------------------------------------------ quantize
quant_parts = [
    header,
    """#define GROUP_MAX_EPS_IQ2_S 1e-8f
#define NGRID_IQ1S 2048
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#define GGML_ASSERT(x) assert(x)
#define GGML_ABORT(...) do { fprintf(stderr, __VA_ARGS__); abort(); } while (0)
enum ggml_type { GGML_TYPE_IQ2_XXS = 0, GGML_TYPE_IQ2_XS, GGML_TYPE_IQ1_S, GGML_TYPE_IQ1_M, GGML_TYPE_IQ2_S = 13 };
typedef struct { uint64_t * grid; int * map; uint16_t * neighbours; } iq2_entry_t;
static iq2_entry_t iq2_data[4] = {{NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}};
""",
    extract_function(quants_c, "static inline int iq2_data_index("),
    extract_function(quants_c, "static inline int iq2_grid_size("),
    extract_function(quants_c, "static inline int nearest_int("),
    extract_function(quants_c, "static int iq2_compare_func("),
    # iq2xs_init_impl carries the kgrid_2bit_1024 table and builds the
    # map/neighbours exactly as the reference quantizer expects them.
    extract_function(quants_c, "void iq2xs_init_impl("),
    extract_function(quants_c, "static int iq2_find_best_neighbour("),
    extract_function(quants_c, "static void quantize_row_iq2_s_impl("),
    extract_function(quants_c, "size_t quantize_iq2_s("),
    extract_function(quants_c, "void quantize_row_iq2_s_ref("),
    """
int main(void) {
    float * in = malloc(1 << 24);
    unsigned char * y = malloc(1 << 24);
    size_t len = fread(in, 4, (1 << 24)/4, stdin);
    size_t n = len - (len % 256);
    if (n == 0) { fprintf(stderr, "bad input len %zu\\n", len); return 1; }
    iq2xs_init_impl(GGML_TYPE_IQ2_S);
    for (size_t off = 0; off < n; off += 256)
        quantize_row_iq2_s_ref(in + off, (block_iq2_s *)(y + (off/256)*82), 256);
    fwrite(y, 1, (n/256)*82, stdout);
    return 0;
}
""",
]
quant_oracle = "\n".join(quant_parts)

os.makedirs(OUT_DIR, exist_ok=True)
for name, src in (("oracle", dequant_oracle), ("quant_oracle", quant_oracle)):
    cpath = os.path.join(OUT_DIR, name + ".c")
    bpath = os.path.join(OUT_DIR, name)
    with open(cpath, "w") as f:
        f.write(src)
    subprocess.run(["cc", "-O2", "-o", bpath, cpath, "-lm"], check=True)
    print(f"built {bpath}")
