//! Build script for the Vulkan backend.
//!
//! At compile time this script compiles every GLSL compute kernel to real SPIR-V
//! using `glslangValidator -V` (the same tool documented in `radv_repro.rs`).
//! The resulting `.spv` blobs are embedded into the crate at compile time via
//! `include_bytes!`, so `compile_glsl_to_spirv` returns genuine SPIR-V with no
//! runtime dependency on an external compiler.
//!
//! All kernels share a single `push_constant` `Params` block so the pipeline
//! layout stays uniform across every entry point. Dynamic per-dispatch values
//! (element count, inner dimension, matmul K, etc.) are supplied via push
//! constants instead of being baked into the shader source.

use std::path::PathBuf;
use std::process::Command;

/// Load a kernel source file. The kernel .comp file already contains
/// its own #version and PARAMS_GLSL block, so we use it as-is.
fn load_kernel(name: &str) -> String {
    let path = PathBuf::from("kernels").join(format!("{name}.comp"));
    std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("Failed to read kernel source: {}", path.display()))
}

/// (kernel name, glsl source). The name is used for the `.comp`/`.spv` file
/// and the generated `include_bytes!` constant.
fn kernels() -> Vec<(&'static str, String)> {
vec![
        ("add", load_kernel("add")),
        ("mul", load_kernel("mul")),
        ("silu_mul", load_kernel("silu_mul")),
        ("rms_norm", load_kernel("rms_norm")),
        ("softmax", load_kernel("softmax")),
        ("embedding", load_kernel("embedding")),
        ("matmul_32", load_kernel("matmul_tile_32")),
        ("matmul_64", load_kernel("matmul_tile_64")),
        ("qkv_attention", load_kernel("qkv_attention")),
        ("mul_scalar", load_kernel("mul_scalar")),
        ("sqrt", load_kernel("sqrt")),
        ("recip", load_kernel("recip")),
        ("rope", load_kernel("rope")),
    ]
}

fn main() {
    println!("cargo:rustc-link-lib=dylib=vulkan");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=kernels/add.comp");
    println!("cargo:rerun-if-changed=kernels/mul.comp");
    println!("cargo:rerun-if-changed=kernels/silu_mul.comp");
    println!("cargo:rerun-if-changed=kernels/rms_norm.comp");
    println!("cargo:rerun-if-changed=kernels/softmax.comp");
    println!("cargo:rerun-if-changed=kernels/embedding.comp");
    println!("cargo:rerun-if-changed=kernels/matmul_tile_32.comp");
    println!("cargo:rerun-if-changed=kernels/matmul_tile_64.comp");
    println!("cargo:rerun-if-changed=kernels/qkv_attention.comp");
    println!("cargo:rerun-if-changed=kernels/mul_scalar.comp");
    println!("cargo:rerun-if-changed=kernels/sqrt.comp");
    println!("cargo:rerun-if-changed=kernels/recip.comp");
    println!("cargo:rerun-if-changed=kernels/rope.comp");
println!("cargo:rerun-if-changed=kernels/matmul_tile_32_bf16.comp");
println!("cargo:rerun-if-changed=kernels/matmul_tile_64_bf16.comp");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));

    let validator = std::env::var("GLSLANG_VALIDATOR")
        .unwrap_or_else(|_| "glslangValidator".to_string());

    let mut gen_code = String::new();
    gen_code.push_str("// @generated by build.rs — do not edit.\n");
    gen_code.push_str("// Real SPIR-V blobs compiled from GLSL via glslangValidator.\n\n");

    let mut any_failed = false;
    for (name, glsl) in kernels() {
        let comp_path = out_dir.join(format!("{name}.comp"));
        let spv_path = out_dir.join(format!("{name}.spv"));
        std::fs::write(&comp_path, glsl.as_bytes()).expect("write .comp");

        let status = Command::new(&validator)
            .arg("-V")
            .arg("--target-env")
            .arg("vulkan1.1")
            .arg(&comp_path)
            .arg("-o")
            .arg(&spv_path)
            .status();

        match status {
            Ok(s) if s.success() => {
                gen_code.push_str(&format!(
                    "pub const SPIRV_{}: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{}.spv\"));\n",
                    sanitize(name),
                    name
                ));
            }
            Ok(s) => {
                eprintln!(
                    "build.rs: glslangValidator failed for kernel `{name}` (status {s}); omitting precompiled blob"
                );
                any_failed = true;
            }
            Err(e) => {
                eprintln!(
                    "build.rs: could not invoke glslangValidator for kernel `{name}`: {e}; omitting precompiled blob"
                );
                any_failed = true;
            }
        }
    }

    let gen_path = out_dir.join("spirv_spv.rs");
    std::fs::write(&gen_path, gen_code).expect("write generated spirv module");

    if any_failed {
        // Surface a clear error so the failure is not silently swallowed.
        panic!(
            "build.rs: one or more Vulkan kernels failed to compile to SPIR-V. \
             Ensure `glslangValidator` is installed and on PATH (or set GLSLANG_VALIDATOR)."
        );
    }
}

fn sanitize(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_lowercase() {
                c.to_ascii_uppercase()
            } else if c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}