#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Params {
    uint size;
    uint dim;
    uint k;
    uint n;
    uint m;
    float eps;
} params;

layout(std430, binding = 0) readonly buffer BufA { float A[]; };
layout(std430, binding = 1) readonly buffer BufB { float B[]; };
layout(std430, binding = 2) writeonly buffer BufOut { float Out[]; };

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.size) return;

    Out[i] = A[i] + B[i];
}
