#version 450

layout(local_size_x = 256) in;

layout(push_constant) uniform Params {
    uint size;
    uint dim;
    uint k;
    uint n;
    uint m;
    float eps;
} params;

layout(std430, binding = 0) readonly buffer X { float x[]; };
layout(std430, binding = 1) writeonly buffer Y { float y[]; };

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= params.size) return;
    y[id] = sqrt(x[id]);
}
